### PR TITLE
samples: rpi_pico: create dedicated boards/rpi_pico/boot_stage2 sample

### PR DESCRIPTION
**Pull request by tejlmand**
Depends on: #41301 (has been squashed as first commit, please ignore)

This commit removes the multi-image stage2 bootloader from the Zephyr
image and instead create a dedicated board specific sample for the
stage2 bootloader.

It reuses the Zephyr build infrastructure, such as Zephyr modules,
toolchain, Kconfig, etc. but not the Zephyr kernel itself.

Signed-off-by: Torsten Rasmussen <Torsten.Rasmussen@nordicsemi.no>

-------------------------------------

@yonsch feel free to give feedback and cherry-pick / squash as you like into https://github.com/zephyrproject-rtos/zephyr/pull/34835.

This PR allows to build the stage2 bootloader using standard tools, like `cmake + ninja / make` or `west build`, for example:
```
$ west build -brpi_pico samples/boards/rpi_pico/boot_stage2/ -p
-- west build: making build dir /projects/github/ncs/zephyr/build pristine
-- west build: generating a build system
Loading Zephyr module(s) (Zephyr base): extensions;west;root;zephyr_module;boards;shields;arch;build_configuration;host-tools;generic_toolchain;kconfig;soc;target_toolchain
-- Found Python3: /usr/bin/python3.8 (found suitable exact version "3.8.10") found components: Interpreter 
-- Cache files will be written to: /home/tejlmand/.cache/zephyr
-- Found west (found suitable version "0.12.0", minimum required is "0.7.1")
-- Board: rpi_pico
-- Found dtc: /usr/bin/dtc (found suitable version "1.5.0", minimum required is "1.4.6")
-- Found toolchain: zephyr 0.13.1 (/opt/zephyr-sdk-0.13.1)
Parsing /projects/github/ncs/zephyr/Kconfig
Loaded configuration '/projects/github/ncs/zephyr/boards/arm/rpi_pico/rpi_pico_defconfig'
Merged configuration '/projects/github/ncs/zephyr/samples/boards/rpi_pico/boot_stage2/prj.conf'
Configuration saved to '/projects/github/ncs/zephyr/build/zephyr/.config'
Kconfig header saved to '/projects/github/ncs/zephyr/build/zephyr/include/generated/autoconf.h'
-- The C compiler identification is GNU 10.3.0
-- The CXX compiler identification is GNU 10.3.0
-- The ASM compiler identification is GNU
-- Found assembler: /opt/zephyr-sdk-0.13.1/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc
-- Configuring done
-- Generating done
-- Build files have been written to: /projects/github/ncs/zephyr/build
-- west build: building application
[3/3] Generating boot_stage2.bin

```

### CODE REVIEW

**Comment by tejlmand** [comment]
@yonsch please take a look at this part, and decide what is needed here:
https://github.com/yonsch/zephyr/blob/f8f9209e3b025cb0b3ad12c3f07d75f096eb5fa5/samples/boards/rpi_pico/boot_stage2/CMakeLists.txt#L68-L75

**Comment by tejlmand** [comment]
Note: this PR just presents the outline, one thing that should be considered is whether the complete kconfig tree should be available in this sample.

In principle it doesn't make sense to have the whole tree, but kept cleaning up this part outside.

Would like some feedback on the approach seen from your viewpoint first.

**Comment by rivimey** [comment]
One comment: this work is basically not board specific and there are at least 3 more boards in the queue waiting to be added** which will need the same cmake files at least. Can the new code be moved under the 'soc' tree instead, where it can be shared nicely?

2 from adafruit, one solderparty; there are many others out there.

**Comment by tejlmand** [comment]
> One comment:

Thanks a lot.
I answered [here](https://github.com/zephyrproject-rtos/zephyr/pull/34835#discussion_r789539200), to make it easier for others to chip in.

**Pull request closed without merging**
